<?php
session_set_cookie_params(array("samesite" => "Strict"));
session_start();
session_regenerate_id(true);
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Annotation Files Merger (Version 2.0)</title>
    <link rel="stylesheet" type="text/css" href="styles/yui-3.18.1-min.css">
<link rel="stylesheet" href="styles/submissionhelper-min.css">
  </head>

  <body class="yui3-skin-sam">
    <div id='hd'>
      <div class="yui3-g">
        <div class="yui3-u-1-2">
          <div class="logo-container">
            <img src="images/GEP_logo.png" alt="GEP Logo" class="logo"/>
            Annotation Files Merger
          </div>
        </div>
        <div class="yui3-u-1-2 release">Version 2.0</div>
      </div>
    </div>

    <div id="bd">
      <div id="systemMessages"></div>

      <div id="basicUploadSection" class="module">
        <form id="uploadForm" class="simpleform" action="upload.php"
              method="POST" enctype="multipart/form-data">

          <p id="instructions">
            Use this tool to combine files generated by the Gene Model Checker into
            a single file for project submission.
          </p>

          <fieldset>
            <legend>Configure the Annotation Files Merger:</legend>
            <ol>
              <li>
                <label for="fileType">File Type:</label>
                <select id="fileType" name="fileType">
                  <option value="gff">GFF Files (.gff)</option>
                  <option value="fasta">Transcript Sequence Files (.fasta)</option>
                  <option value="pep">Peptide Sequence Files (.pep)</option>
                  <option value="vcf">Variant Call Format (.vcf.txt)</option>
                </select>
              </li>
            </ol>
          </fieldset>

          <fieldset id="selectfiles" class="uploader hidden">
            <legend>Select the files to merge:</legend>
            <ul>
              <li class="html5uploader hidden"><div id="fileListDDmessage"></div></li>
              <li><div id="selectFilesButtonContainer"></div></li>
            </ul>
          </fieldset>

          <fieldset id="filelistFieldSet" class="simpleuploader">
            <legend>Select the Files to merge:</legend>
            <ol>
              <li id="numFilesField">
                <label for="numFiles">Number of Files to Upload:</label>
                <input name="numFiles" id="numFiles" type="text" value="1">
              </li>
            </ol>
            <ol id="fileUploadFields">
              <li>
                <label>File 1: </label>
                <input name="ufile[]" type="file" size="50" class="ufiles" />
              </li>
            </ol>
            <input type="hidden" id="sessionid"
                   name="sessionid" value='<?php echo session_id(); ?>'/>
          </fieldset>

          <div id="filelist" class="uploader hidden">
            <table id="filelist-table">
              <caption>List of files to merge:</caption>
              <thead>
                <tr><th>File name</th><th>File size</th><th>Percent uploaded</th></tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>

          <div id="uploaderContainer">
            <div id="uploadFilesButtonContainer">
              <button type="button" id="uploadFilesButton" class="yui3-button"
                      style="width:150px; height:30px;">Merge Files</button>

              <a style="background-color:#68C2FF;" class="yui3-button"
                 href="./index.php">Reset</a>
            </div>
          </div>
        </form>
      </div>

      <div id="resultsPanel" class="module hidden">
        <h1>File Merge Results</h1>
        <div class="module">
          <h2>Download merged file</h2>
          <p>
            Right click on the <a id="mergedFileLink" href="#" download>Merged File link</a>
            and select "Save Link As..." to save the merged file.
          </p>
        </div>

        <div id="browserLink" class="hidden">
          <div id="checklistPanel" class="module hidden">
            <h2>Isoforms checklist</h2>
            <div id="checklistContainer"></div>
          </div>

          <div id="overlapContainer" class="module hidden">
            <h2>Overlapping features found in merged GFF file</h2>
            <em>
              Please provide an explanation for the following overlapping genes
              in the GEP Annotation Report:
            </em>
          </div>

          <div class="module">
            <h2>Show merged file in the Genome Browser</h2>

            <div id="browserLinkSection" name="browserLinkSection">
              <p>Click on the "Show Track" button to view the merged file in the Genome Browser</p>
            </div>

            <div id="browserSelectSection" name="browserSelectSection">
              <p>Select the project region and then click "Show Track"</p>
              <select id="browserLinkSelect" name="browserLinkSelect">
                <option value='_unselected'>Select a Project Region...</option>
                <option value='DbipPB2'>D. bipectinata Muller D (Aug. 2021)</option>
                <option value='DbipPB1'>D. bipectinata Muller F (Jan. 2021)</option>
                <option value='DanaPB2'>D. ananassae Muller D (Mar. 2020)</option>
                <option value='DanaPB1'>D. ananassae Muller F (Sep. 2019)</option>
                <option value='dm6'>D. melanogaster Aug. 2014 (BDGP Release 6 + ISO1 MT/dm6)</option>
                <option value='DereCAF1'>D. erecta May 2011 (Agencourt dere_caf1/DereCAF1)</option>
                <option value='DsecCAF1'>D. sechellia May 2011 (Broad dsec_caf1/DsecCAF1)</option>
                <option value='DsimGB2'>D. simulans May 2017 (Princeton University ASM75419v2/DsimGB2)</option>
                <option value='DyakCAF1'>D. yakuba May 2011 (WUGSC dyak_caf1/DyakCAF1)</option>
                <option value='DanaCAF1'>D. ananassae May 2011 (Agencourt dana_caf1/DanaCAF1)</option>
                <option value='DbipGB2'>D. bipectinata Apr. 2013 (BCM-HGSC/Dbip_2.0)</option>
                <option value='DeleGB2'>D. elegans Apr. 2013 (BCM-HGSC/Dele_2.0)</option>
                <option value='DeugGB2'>D. eugracilis Apr. 2013 (BCM-HGSC/Deug_2.0)</option>
                <option value='DficGB2'>D. ficusphila Apr. 2013 (BCM-HGSC/Dfic_2.0)</option>
                <option value='DkikGB2'>D. kikkawai Apr. 2013 (BCM-HGSC/Dkik_2.0)</option>
                <option value='DserGB1'>D. serrata Apr. 2017 (University of Queensland Dser1.0/DserGB1)</option>
                <option value='DrhoGB2'>D. rhopaloa Apr. 2013 (BCM-HGSC/Drho_2.0)</option>
                <option value='DbiaGB2'>D. biarmipes Apr. 2013 (BCM-HGSC/Dbia_2.0)</option>
                <option value='DsuzGB1'>D. suzukii Sep. 2013 (BGI/Dsuz_1.0)</option>
                <option value='DtakGB2'>D. takahashii Apr. 2013 (BCM-HGSC/Dtak_2.0)</option>
                <option value='DobsGB1'>D. obscura July 2017 (NIG Dobs_1.0/DobsGB1)</option>
                <option value='DmirGB2'>D. miranda Apr. 2013 (UC Berkeley DroMir_2.2/DmirGB2)</option>
                <option value='DperCAF1'>D. persimilis May 2011 (Broad dper_caf1/DperCAF1)</option>
                <option value='DpseGB3'>D. pseudoobscura Apr. 2013 (BCM-HGSC Dpse_3.0/DpseGB3)</option>
                <option value='DwilCAF1'>D. willistoni May 2011 (JCVI dwil_caf1/DwilCAF1)</option>
                <option value='DbusGB1'>D. busckii Sep. 2015 (UC Berkeley ASM127793v1/DbusGB1)</option>
                <option value='DhydGB1'>D. hydei Nov. 2017 (UC Davis ASM278046v1/DhydGB1)</option>
                <option value='DariGB1'>D. arizonae June 2016 (UNAM ASM165402v1/DariGB1)</option>
                <option value='DmojCAF1'>D. mojavensis May 2011 (Agencourt dmoj_caf1/DmojCAF1)</option>
                <option value='DnavGB1'>D. navojoa June 2016 (UNAM ASM165401v1/DnavGB1)</option>
                <option value='DvirCAF1'>D. virilis Sep. 2011 (Agencourt dvir_caf1/DvirCAF1)</option>
                <option value='DgriCAF1'>D. grimshawi May 2011 (Agencourt dgri_caf1/DgriCAF1)</option>
                <option value='DanaRS2'>D. ananassae Oct. 2018 (AGI/DanaRS2)</option>
                <option value='DbipPurged1'>D. bipectinata Dec. 2020 (GEP/DbipPurged1)</option>
                <option value='Dere2'>D. erecta Dot (Aug. 2006)</option>
                <option value='Dere3'>D. erecta 3L Control (Apr. 2007)</option>
                <option value='Dere4'>D. erecta 3L Extended (Jan. 2008)</option>
                <option value='Dere6'>D. erecta 2nd 3L Control (Nov. 2011)</option>
                <option value='Deug1'>D. eugracilis Dot (Jan. 2017)</option>
                <option value='Deug2'>D. eugracilis 3L Control (Aug. 2017)</option>
                <option value='Dbia3'>D. biarmipes Dot (Aug. 2013)</option>
                <option value='Dbia4'>D. biarmipes 3L Control (Jan. 2014)</option>
                <option value='Dbia2'>D. biarmipes Dot (Aug. 2012) (Deprecated)</option>
                <option value='Dtak1'>D. takahashii Dot (Jan. 2018)</option>
                <option value='Dtak2'>D. takahashii 3L Control (Aug. 2018)</option>
                <option value='Dele1'>D. elegans Dot (Jan. 2015)</option>
                <option value='Dele2'>D. elegans 3L Control (Aug. 2015)</option>
                <option value='Dfic1'>D. ficusphila Dot (Jan. 2016)</option>
                <option value='Dfic2'>D. ficusphila 3L Control (Aug. 2016)</option>
                <option value='Dmoj4'>D. mojavensis Dot (Sep. 2008)</option>
                <option value='Dmoj5'>D. mojavensis 3L Control (Apr. 2011)</option>
                <option value='Dvir3'>D. virilis Dot (Mar. 2006 (DEMO))</option>
                <option value='drosample'>D. virilis Dot Walkthrough (Mar. 2005)</option>
                <option value='Dgri3'>D. grimshawi Dot (Mar. 2009)</option>
                <option value='Dgri5'>D. grimshawi Dot (Sep. 2010)</option>
              </select>
            </div>

            <div class="showTrackButton-container">
              <a id="browserLinkAnchor" target='_blank' href="#"
                class="yui3-button">Show Track</a>
            </div>
          </div>
        </div>

        <a href="./index.php" class="yui3-button">Merge another set of files</a>
      </div>
    </div>

    <div id="ft">
      <p>
        | <a href="https://thegep.org">GEP Home Page</a> |
          <a href="https://community.gep.wustl.edu/repository/documentations/Annotation_Files_Merger_User_Guide.pdf">User Guide</a> |
      </p>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/yui/3.18.1/yui/yui-min.js"></script>
    <script src="scripts/submissionhelper-min.js"></script>
  </body>
</html>
<?php session_destroy(); ?>
